<!DOCTYPE html><html lang="en"><head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="images/favicon.png">
    <!-- Bootstrap CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/stylelog.css" rel="stylesheet">
    <link href="css/all.min.css" rel="stylesheet">
    <link href="css/animate.css" rel="stylesheet">
    <link href="css/stylelog_1.css" rel="stylesheet">
    <link href="css/responsive.css" rel="stylesheet">
    
    
    <title> <?= $title ?></title>
</head>

<body data-scroll-animation="true">
<?= include $page ; ?>
</body>
</html>