<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp" rel="stylesheet">
    <link rel="stylesheet" href="styles/styleborrow.css">
    
    <title>Borrow and Return - Library Management</title>
</head>
<body>


<div class="container">
<?php 
    include "Borrow.phtml";
?>
</div>

</body>
</html>
