<!DOCTYPE html><html lang="en"><head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="images/favicon.png">
    <!-- Bootstrap CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/responsive.css" rel="stylesheet">
    <link href="css/animate.css" rel="stylesheet">
    <link href="css/all.min.css" rel="stylesheet">
    <link href="css/slick.css" rel="stylesheet">
    <link href="css/slick-theme.css" rel="stylesheet">
    <link href="css/style_1.css" rel="stylesheet">
    <link href="css/themify-icons.css" rel="stylesheet">
    
    <link href="css/swiper.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
    <link href="css/style_2.css" rel="stylesheet">
    
    <title>IsetBooks</title>
</head>

<body data-scroll-animation="true">
<?= include $page ; ?>
</body>
</html>