<div id="preloader">
        <div id="ctn-preloader" class="ctn-preloader">
            <div class="round_spinner">
                <div class="spinner"></div>
                <div class="text">
                    <img src="images/favicon.png" alt="Image">
                    <h4><span>IsetBokks</span></h4>
                </div>
            </div>
            <h2 class="head">Did You Know?</h2>
            <p></p>
        </div>
    </div>

    <div class="body_wrapper">
        <div class="login-area">
            <div class="bg-shapes">
                <img class="wow fadeIn" src="images/heart-shape-01.png" alt="Image">
                <img class="wow fadeInLeft" src="images/heart-shape-02.png" alt="Image">
                <img class="wow fadeInLeft" src="images/heart-shape-03.png" alt="Image">
                <img class="wow " src="images/heart-shape-04.png" alt="Image">
            </div>
            <div class="login-wrapper">
                <div class="login-left">
                    <a href="index.html" class="logo"><img src="images/logo-dark.svg" alt="Image"></a>
                    <h2 class="title">Login to Your Account</h2>
                    <div class="sibtitle">Welcome Back! Select Method to login:</div>

                    <div class="divider"><span></span></div>
                    <form action="loginuser.php" method="POST">
                        <div class="input-field">
                            <input type="email" class="form-control" placeholder="Email" name="email">
                        </div>
                        <div class="input-field pass-field-with-icon">
                            <input type="password" class="form-control" id="toggle_passowrd_field" placeholder="Password" name="password">
                            <i data-toggletarget="#toggle_passowrd_field" class="icon fas fa-eye toggle-password"></i>
                        </div>
                       
                        <button type="submit" class="bj_theme_btn w-100 border-0">Log In</button>
                    </form>
                    <div class="new-user">
                        New user?<a href="registreuser.php"> Create an account</a>
                    </div>
                </div>
                <div class="login-right">
                    <img src="images/login-img.png" alt="Image">
                </div>
            </div>
        </div>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->
    <script src="js/jquery-3.6.0.min.js"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->

    <script src="js/preloader.js"></script>
    <script src="js/popper.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/wow.min.js"></script>
    <script src="js/custom.js"></script>
