<div id="preloader">
        <div id="ctn-preloader" class="ctn-preloader">
            <div class="round_spinner">
                <div class="spinner"></div>
                <div class="text">
                    <img src="images/favicon.png" alt="Image">
                    <h4><span>IsetBooks</span></h4>
                </div>
            </div>
            <h2 class="head">Did You Know?</h2>
            <p></p>
        </div>
    </div>

    <div class="body_wrapper">
        <div class="login-area registration-area">
            <div class="login-wrapper">
                <div class="login-left">
                    <a href="index.html" class="logo"><img src="images/logo-dark.svg" alt="Image"></a>
                    <h2 class="title">Sign Up to Bookjar</h2>
                    <div class="sibtitle">Create Your Account with Just Few Steps</div>

                    <div class="divider"><span></span></div>
                    <form action="registreuser.php" method="POST" enctype="multipart/form-data">
                        <div class="input-field">
                            <input type="text" class="form-control" placeholder="Name" name="name" required>
                        </div>
                        <div class="input-field">
                            <input type="email" class="form-control" placeholder="Email" name="email" required>
                        </div>
                        <div class="input-field">
                            <input type="password" class="form-control" placeholder="Password" name="password" required>
                        </div>
                        <div class="input-field">
                            <input type="password" class="form-control" placeholder="Confirm Password" name="confirm_password" required>
                        </div>
                        <div class="d-flex justify-content-between input-field">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked">

                            <label class="form-check-label" for="flexCheckChecked" >I agree to the <a href="privacy.php">Privacy Policy</a>.</label>
                        </div>
                        </div>
                        
                        <button type="submit" class="bj_theme_btn w-100 border-0">Register</button>
                    </form>
                    

                    <div class="new-user">
                        Already have an account?<a href="loginuser.php"> Login Here</a>
                    </div>
                </div>
                <div class="login-right">
                    <img class="mt-auto" src="images/reginstration-img.png" alt="Image">
                </div>
            </div>
        </div>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->
    <script src="js/jquery-3.6.0.min.js"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->

    <script src="js/preloader.js"></script>
    <script src="js/popper.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/wow.min.js"></script>
    <script src="js/custom.js"></script>